# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.25.2/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.25.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/alex/code/terminal_task_manager

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/alex/code/terminal_task_manager

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.25.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.25.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/alex/code/terminal_task_manager/CMakeFiles /Users/alex/code/terminal_task_manager//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/alex/code/terminal_task_manager/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TaskManagerTerminal

# Build rule for target.
TaskManagerTerminal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TaskManagerTerminal
.PHONY : TaskManagerTerminal

# fast build rule for target.
TaskManagerTerminal/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TaskManagerTerminal.dir/build.make CMakeFiles/TaskManagerTerminal.dir/build
.PHONY : TaskManagerTerminal/fast

src/BusinessLogicLayer.o: src/BusinessLogicLayer.cpp.o
.PHONY : src/BusinessLogicLayer.o

# target to build an object file
src/BusinessLogicLayer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TaskManagerTerminal.dir/build.make CMakeFiles/TaskManagerTerminal.dir/src/BusinessLogicLayer.cpp.o
.PHONY : src/BusinessLogicLayer.cpp.o

src/BusinessLogicLayer.i: src/BusinessLogicLayer.cpp.i
.PHONY : src/BusinessLogicLayer.i

# target to preprocess a source file
src/BusinessLogicLayer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TaskManagerTerminal.dir/build.make CMakeFiles/TaskManagerTerminal.dir/src/BusinessLogicLayer.cpp.i
.PHONY : src/BusinessLogicLayer.cpp.i

src/BusinessLogicLayer.s: src/BusinessLogicLayer.cpp.s
.PHONY : src/BusinessLogicLayer.s

# target to generate assembly for a file
src/BusinessLogicLayer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TaskManagerTerminal.dir/build.make CMakeFiles/TaskManagerTerminal.dir/src/BusinessLogicLayer.cpp.s
.PHONY : src/BusinessLogicLayer.cpp.s

src/DataSourceLayer.o: src/DataSourceLayer.cpp.o
.PHONY : src/DataSourceLayer.o

# target to build an object file
src/DataSourceLayer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TaskManagerTerminal.dir/build.make CMakeFiles/TaskManagerTerminal.dir/src/DataSourceLayer.cpp.o
.PHONY : src/DataSourceLayer.cpp.o

src/DataSourceLayer.i: src/DataSourceLayer.cpp.i
.PHONY : src/DataSourceLayer.i

# target to preprocess a source file
src/DataSourceLayer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TaskManagerTerminal.dir/build.make CMakeFiles/TaskManagerTerminal.dir/src/DataSourceLayer.cpp.i
.PHONY : src/DataSourceLayer.cpp.i

src/DataSourceLayer.s: src/DataSourceLayer.cpp.s
.PHONY : src/DataSourceLayer.s

# target to generate assembly for a file
src/DataSourceLayer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TaskManagerTerminal.dir/build.make CMakeFiles/TaskManagerTerminal.dir/src/DataSourceLayer.cpp.s
.PHONY : src/DataSourceLayer.cpp.s

src/UserInterfaceLayer.o: src/UserInterfaceLayer.cpp.o
.PHONY : src/UserInterfaceLayer.o

# target to build an object file
src/UserInterfaceLayer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TaskManagerTerminal.dir/build.make CMakeFiles/TaskManagerTerminal.dir/src/UserInterfaceLayer.cpp.o
.PHONY : src/UserInterfaceLayer.cpp.o

src/UserInterfaceLayer.i: src/UserInterfaceLayer.cpp.i
.PHONY : src/UserInterfaceLayer.i

# target to preprocess a source file
src/UserInterfaceLayer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TaskManagerTerminal.dir/build.make CMakeFiles/TaskManagerTerminal.dir/src/UserInterfaceLayer.cpp.i
.PHONY : src/UserInterfaceLayer.cpp.i

src/UserInterfaceLayer.s: src/UserInterfaceLayer.cpp.s
.PHONY : src/UserInterfaceLayer.s

# target to generate assembly for a file
src/UserInterfaceLayer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TaskManagerTerminal.dir/build.make CMakeFiles/TaskManagerTerminal.dir/src/UserInterfaceLayer.cpp.s
.PHONY : src/UserInterfaceLayer.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TaskManagerTerminal.dir/build.make CMakeFiles/TaskManagerTerminal.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TaskManagerTerminal.dir/build.make CMakeFiles/TaskManagerTerminal.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TaskManagerTerminal.dir/build.make CMakeFiles/TaskManagerTerminal.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... TaskManagerTerminal"
	@echo "... src/BusinessLogicLayer.o"
	@echo "... src/BusinessLogicLayer.i"
	@echo "... src/BusinessLogicLayer.s"
	@echo "... src/DataSourceLayer.o"
	@echo "... src/DataSourceLayer.i"
	@echo "... src/DataSourceLayer.s"
	@echo "... src/UserInterfaceLayer.o"
	@echo "... src/UserInterfaceLayer.i"
	@echo "... src/UserInterfaceLayer.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

